### ISSUE TITLE
bug when there is y < 0

### ISSUE THREAD

**Issue by chenqinkai** [mrepetto94/sentiment_modelling#1]
In your beautifultools.py, from line 542 to 546
```
        # Binarize the order to label whether an observation belongs
        # to a client 1 or 0 a prospect
        y = y.copy()
        ybin = y
        ybin[ybin > 0] = 1
```

When there is y < 0, it will regress on the value of y instead of a 0.
I think you should add
```
ybin[ybin <= 0] = 0
```
at the end.

Hope it makes sense.

**Comment by mrepetto94** [comment]
You're indeed right! I fixed it, thanks
